// Generated by CoffeeScript 1.9.1
(function() {
  var hello;

  hello = function() {
    var a, results;
    a = 10;
    results = [];
    while (a--) {
      console.log('test');
      results.push(console.log('hello'));
    }
    return results;
  };

  hello();

}).call(this);
